export const DEFAULT_PATH = '/'
export const ADD_EXPENSE_PATH = '/AddExpense'
export const EXPENSES_PATH = '/Expenses'
export const OVERVIEW_PATH = '/Overview'
export const BUDGET_PATH = '/Budget'
export const WALLET_PATH = '/Wallet'